name: Mirror Repo

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to New Repo
        run: |
          git push --mirror https://${{ secrets.PAT }}@github.com/${{ github.repository_owner }}/my-rainmaker-repo-2.git
